name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang 18
      run: wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s -- 18

    - name: Configure CMake
      run: cmake --preset=default

    - name: Build
      run: cmake --build --preset=default

    - name: Test
      run: cmake --build --target=test --preset=default
